// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'browse_document.rules.freezed.dart';

@freezed
abstract class BrowseDocument with _$BrowseDocument {
  const BrowseDocument._();

  const factory BrowseDocument({
    @Default(const []) List<SubmissionPreview> submissions,
    @Default(const {}) Map<String, ParseException> failed,
    ReadReport? report,
  }) = _BrowseDocument;

  static const String ruleType = 'browseDocument';

  static BrowseDocument? fromOutcome(
    ParseOutcome outcome, {
    ReadReport? report,
  }) {
    return BrowseDocument(
      submissions: [
        for (final Object? item
            in (outcome['submissions'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      failed: outcome.failed,
      report: report,
    );
  }
}
