// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/favorite.rules.dart';

part 'favorites_document.rules.freezed.dart';

@freezed
abstract class FavoritesDocument with _$FavoritesDocument {
  const FavoritesDocument._();

  const factory FavoritesDocument({
    @Default(const []) List<Favorite> favorites,
    @Default(const {}) Map<String, ParseException> failed,
    DocumentErrors? errors,
  }) = _FavoritesDocument;

  static const String ruleType = 'favoritesDocument';

  static FavoritesDocument? fromOutcome(
    ParseOutcome outcome, {
    DocumentErrors? errors,
  }) {
    return FavoritesDocument(
      favorites: [
        for (final Object? item
            in (outcome['favorites'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Favorite.fromOutcome(item),
      ],
      failed: outcome.failed,
      errors: errors,
    );
  }
}
