// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'favorite.rules.freezed.dart';

@freezed
abstract class Favorite with _$Favorite {
  const Favorite._();

  const factory Favorite({
    /// Identifies a favourite rather than the submission, and exists only
    /// where a submission appears as somebody's favourite.
    required int id,
    required SubmissionPreview submission,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Favorite;

  static const String ruleType = 'favorite';

  static Favorite? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    final SubmissionPreview? submission = switch (outcome['submission']) {
      final ParseOutcome child => SubmissionPreview.fromOutcome(child),
      _ => null,
    };
    if (submission == null) return null;
    return Favorite(id: id, submission: submission, failed: outcome.failed);
  }
}
