// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'folder.rules.freezed.dart';

@freezed
abstract class Folder with _$Folder {
  const Folder._();

  const factory Folder({
    required int id,
    required String name,

    /// The folder name as FA writes it into the url. FA routes by the id
    /// alone, and writes a placeholder for names it cannot transliterate.
    required String slug,

    /// The url name of the member who owns the folder.
    required String user,

    /// Counts every rating, so it exceeds what a listing shows a reader
    /// whose settings hide some of them.
    int? count,

    /// The heading the member filed the folder under. Only the gallery
    /// sidebar carries it, and folders outside any heading have none.
    String? group,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Folder;

  static const String entity = 'folder';

  static Folder? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    final String? slug = outcome.get<String>('slug');
    if (slug == null) return null;
    final String? user = outcome.get<String>('user');
    if (user == null) return null;
    return Folder(
      id: id,
      name: name,
      slug: slug,
      user: user,
      count: outcome.get<int>('count'),
      group: outcome.get<String>('group'),
      failed: outcome.failed,
    );
  }
}
