// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'folder_entry.rules.freezed.dart';

/// A row in the gallery sidebar. FA renders the open folder as plain text
/// without a link, so that row carries no user, id or slug.
@freezed
abstract class FolderEntry with _$FolderEntry {
  const FolderEntry._();

  const factory FolderEntry({
    required String name,
    int? count,
    String? group,
    int? id,
    String? slug,
    String? user,
    @Default(const {}) Map<String, String> failed,
  }) = _FolderEntry;

  static const String entity = 'folderEntry';

  static FolderEntry? fromOutcome(ParseOutcome outcome) {
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return FolderEntry(
      name: name,
      count: outcome.get<int>('count'),
      group: outcome.get<String>('group'),
      id: outcome.get<int>('id'),
      slug: outcome.get<String>('slug'),
      user: outcome.get<String>('user'),
      failed: outcome.failed,
    );
  }
}
