// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'folder_row.rules.freezed.dart';

/// A row in the gallery sidebar. FA renders the open folder as plain text
/// without a link, so that row carries no user, id or slug.
@freezed
abstract class FolderRow with _$FolderRow {
  const FolderRow._();

  const factory FolderRow({
    required String name,
    int? count,
    String? group,
    int? id,
    String? slug,
    String? user,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _FolderRow;

  static const String ruleType = 'folderRow';

  static FolderRow? fromOutcome(ParseOutcome outcome) {
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return FolderRow(
      name: name,
      count: outcome.get<int>('count'),
      group: outcome.get<String>('group'),
      id: outcome.get<int>('id'),
      slug: outcome.get<String>('slug'),
      user: outcome.get<String>('user'),
      failed: outcome.failed,
    );
  }
}
