// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'frontpage_document.rules.freezed.dart';

@freezed
abstract class FrontpageDocument with _$FrontpageDocument {
  const FrontpageDocument._();

  const factory FrontpageDocument({
    @Default(const []) List<SubmissionPreview> submissions,
    @Default(const {}) Map<String, ParseException> failed,
    DocumentErrors? errors,
  }) = _FrontpageDocument;

  static const String ruleType = 'frontpageDocument';

  static FrontpageDocument? fromOutcome(
    ParseOutcome outcome, {
    DocumentErrors? errors,
  }) {
    return FrontpageDocument(
      submissions: [
        for (final Object? item
            in (outcome['submissions'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      failed: outcome.failed,
      errors: errors,
    );
  }
}
