// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/folder_row.rules.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'gallery_document.rules.freezed.dart';

@freezed
abstract class GalleryDocument with _$GalleryDocument {
  const GalleryDocument._();

  const factory GalleryDocument({
    @Default(const []) List<SubmissionPreview> submissions,
    @Default(const []) List<FolderRow> folders,
    @Default(const {}) Map<String, ParseException> failed,
    DocumentErrors? errors,
  }) = _GalleryDocument;

  static const String ruleType = 'galleryDocument';

  static GalleryDocument? fromOutcome(
    ParseOutcome outcome, {
    DocumentErrors? errors,
  }) {
    return GalleryDocument(
      submissions: [
        for (final Object? item
            in (outcome['submissions'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      folders: [
        for (final Object? item
            in (outcome['folders'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?FolderRow.fromOutcome(item),
      ],
      failed: outcome.failed,
      errors: errors,
    );
  }
}
