// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'mini_gallery.rules.freezed.dart';

/// The strip of neighbouring submissions on a submission page.
@freezed
abstract class MiniGallery with _$MiniGallery {
  const MiniGallery._();

  const factory MiniGallery({
    required String link,

    /// Which listing the neighbours come from, such as the main gallery.
    required String name,
    int? count,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _MiniGallery;

  static const String entity = 'miniGallery';

  static MiniGallery? fromOutcome(ParseOutcome outcome) {
    final String? link = outcome.get<String>('link');
    if (link == null) return null;
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return MiniGallery(
      link: link,
      name: name,
      count: outcome.get<int>('count'),
      failed: outcome.failed,
    );
  }
}
