// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'mini_gallery.rules.freezed.dart';

/// The strip of neighbouring submissions on a submission page.
@freezed
abstract class MiniGallery with _$MiniGallery {
  const MiniGallery._();

  const factory MiniGallery({
    required String link,

    /// Which listing the neighbours come from, such as the main gallery.
    required String name,
    int? count,
    @Default(const []) List<SubmissionPreview> newer,
    @Default(const []) List<SubmissionPreview> older,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _MiniGallery;

  static const String ruleType = 'miniGallery';

  static MiniGallery? fromOutcome(ParseOutcome outcome) {
    final String? link = outcome.get<String>('link');
    if (link == null) return null;
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return MiniGallery(
      link: link,
      name: name,
      count: outcome.get<int>('count'),
      newer: [
        for (final Object? item
            in (outcome['newer'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      older: [
        for (final Object? item
            in (outcome['older'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      failed: outcome.failed,
    );
  }
}
