// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:furlovin/comment/data/comment.rules.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission.rules.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

abstract final class BrowseSlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'browse',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class GallerySlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'gallery',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class FavoritesSlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'favorites',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class SearchSlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'search',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class FrontpageSlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'frontpage',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class SubmissionsSlots {
  static const ListSlot<SubmissionPreview> submissions = ListSlot(
    'submissions',
    'submissions',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );
}

abstract final class SubmissionSlots {
  static const SingleSlot<Submission> submission = SingleSlot(
    'submission',
    'submission',
    'submission',
    Submission.fromOutcome,
  );

  static const ListSlot<SubmissionPreview> related = ListSlot(
    'submission',
    'related',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );

  static const ListSlot<Comment> comments = ListSlot(
    'submission',
    'comments',
    'comment',
    Comment.fromOutcome,
  );
}
