// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';

part 'search_document.rules.freezed.dart';

@freezed
abstract class SearchDocument with _$SearchDocument {
  const SearchDocument._();

  const factory SearchDocument({
    @Default(const []) List<SubmissionPreview> submissions,
    @Default(const {}) Map<String, ParseException> failed,
    DocumentErrors? errors,
  }) = _SearchDocument;

  static const String ruleType = 'searchDocument';

  static SearchDocument? fromOutcome(
    ParseOutcome outcome, {
    DocumentErrors? errors,
  }) {
    return SearchDocument(
      submissions: [
        for (final Object? item
            in (outcome['submissions'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      failed: outcome.failed,
      errors: errors,
    );
  }
}
