// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_rating.rules.dart';
import 'package:furlovin/submission/data/submission_type.rules.dart';

part 'submission_preview.rules.freezed.dart';

/// A submission as it appears in a listing.
@freezed
abstract class SubmissionPreview with _$SubmissionPreview {
  const SubmissionPreview._();

  const factory SubmissionPreview({
    /// The submission's numeric identifier.
    required int id,

    /// Absolute url of the submission page.
    required String link,

    /// The submission's content rating.
    required SubmissionRating rating,

    /// Absolute url of the thumbnail. The size segment constrains the
    /// longest edge to that many pixels.
    required String thumbnail,

    /// The url form of the name of whoever posted the submission,
    /// lowercased and with underscores removed.
    required String uploader,

    /// Identifies a favourite rather than the submission, and exists only
    /// where a submission appears as somebody's favourite.
    int? favouriteId,

    /// Thumbnail height in pixels, which the site fixes at 200.
    double? thumbnailHeight,

    /// Thumbnail width in pixels, as declared by the site rather than
    /// measured from the image.
    double? thumbnailWidth,

    /// Listing titles are sanitised by the site and may lose leading
    /// punctuation. The submission page carries the canonical title.
    String? title,

    /// Content type, such as image, text, music or flash.
    SubmissionType? type,

    /// The name of whoever posted the submission, as displayed.
    String? uploaderName,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _SubmissionPreview;

  static const String entity = 'submissionPreview';

  static SubmissionPreview? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    final String? link = outcome.get<String>('link');
    if (link == null) return null;
    final SubmissionRating? rating = SubmissionRating.byName(
      outcome.get<String>('rating'),
    );
    if (rating == null) return null;
    final String? thumbnail = outcome.get<String>('thumbnail');
    if (thumbnail == null) return null;
    final String? uploader = outcome.get<String>('uploader');
    if (uploader == null) return null;
    return SubmissionPreview(
      id: id,
      link: link,
      rating: rating,
      thumbnail: thumbnail,
      uploader: uploader,
      favouriteId: outcome.get<int>('favouriteId'),
      thumbnailHeight: outcome.get<double>('thumbnailHeight'),
      thumbnailWidth: outcome.get<double>('thumbnailWidth'),
      title: outcome.get<String>('title'),
      type: SubmissionType.byName(outcome.get<String>('type')),
      uploaderName: outcome.get<String>('uploaderName'),
      failed: outcome.failed,
    );
  }
}
