// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

/// The content rating the site assigns to a submission.
enum SubmissionRating {
  general,
  mature,
  adult;

  static SubmissionRating? byName(String? name) =>
      name == null ? null : values.asNameMap()[name];
}
