// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/comment/data/comment.rules.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/folder.rules.dart';
import 'package:furlovin/submission/data/mini_gallery.rules.dart';
import 'package:furlovin/submission/data/submission.rules.dart';

part 'submission_document.rules.freezed.dart';

@freezed
abstract class SubmissionDocument with _$SubmissionDocument {
  const SubmissionDocument._();

  const factory SubmissionDocument({
    required Submission submission,
    @Default(const []) List<Comment> comments,
    @Default(const []) List<Folder> folders,
    MiniGallery? miniGallery,
    @Default(const {}) Map<String, ParseException> failed,
    DocumentErrors? errors,
  }) = _SubmissionDocument;

  static const String ruleType = 'submissionDocument';

  static SubmissionDocument? fromOutcome(
    ParseOutcome outcome, {
    DocumentErrors? errors,
  }) {
    final Submission? submission = switch (outcome['submission']) {
      final ParseOutcome child => Submission.fromOutcome(child),
      _ => null,
    };
    if (submission == null) return null;
    return SubmissionDocument(
      submission: submission,
      comments: [
        for (final Object? item
            in (outcome['comments'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Comment.fromOutcome(item),
      ],
      folders: [
        for (final Object? item
            in (outcome['folders'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Folder.fromOutcome(item),
      ],
      miniGallery: switch (outcome['miniGallery']) {
        final ParseOutcome child => MiniGallery.fromOutcome(child),
        _ => null,
      },
      failed: outcome.failed,
      errors: errors,
    );
  }
}
