// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_rating.rules.dart';
import 'package:furlovin/submission/data/submission_type.rules.dart';

part 'submission.rules.freezed.dart';

/// A submission as its own page carries it.
@freezed
abstract class Submission with _$Submission {
  const Submission._();

  const factory Submission({
    /// Absolute url of the submitted file at full resolution.
    required String file,

    /// The submission's numeric identifier.
    required int id,

    /// The submission's content rating.
    required SubmissionRating rating,

    /// The submission's title, free of the padding the page markup adds.
    required String title,

    /// The url form of the name of whoever posted the submission,
    /// lowercased and with underscores removed.
    required String uploader,

    /// The kind of work, as the uploader filed it.
    String? category,

    /// How many comments the submission carries.
    int? comments,

    /// The rendered description, as markup rather than text.
    String? description,

    /// The file's extension, without a leading dot.
    String? extension,

    /// How many people have favourited the submission.
    int? favorites,

    /// Absolute url that adds or removes the submission from your
    /// favourites. The site only writes one of the two, so which it is
    /// says whether you have favourited it already. Absent when signed
    /// out.
    String? favouriteLink,

    /// Absent when signed out.
    bool? favourited,

    /// The size of the uploaded file, as FA renders it.
    String? fileSize,

    /// Absolute url that opens a new note to whoever posted it. Absent
    /// when signed out.
    String? noteLink,

    /// When the submission was posted.
    DateTime? posted,

    /// Absolute url of a reduced copy of the submitted file.
    String? preview,

    /// The image's pixel dimensions, as FA renders them.
    String? resolution,

    /// The species the uploader filed the work under.
    String? species,

    /// Keywords the uploader attached to the submission.
    List<String>? tags,

    /// The subject matter the uploader filed the work under.
    String? theme,

    /// The kind of content a submission holds.
    SubmissionType? type,

    /// Absolute url of the avatar of whoever posted the submission.
    String? uploaderAvatar,

    /// The name of whoever posted the submission, as displayed.
    String? uploaderName,

    /// How many times the submission has been viewed.
    int? views,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Submission;

  static const String entity = 'submission';

  static Submission? fromOutcome(ParseOutcome outcome) {
    final String? file = outcome.get<String>('file');
    if (file == null) return null;
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    final SubmissionRating? rating = SubmissionRating.byName(
      outcome.get<String>('rating'),
    );
    if (rating == null) return null;
    final String? title = outcome.get<String>('title');
    if (title == null) return null;
    final String? uploader = outcome.get<String>('uploader');
    if (uploader == null) return null;
    return Submission(
      file: file,
      id: id,
      rating: rating,
      title: title,
      uploader: uploader,
      category: outcome.get<String>('category'),
      comments: outcome.get<int>('comments'),
      description: outcome.get<String>('description'),
      extension: outcome.get<String>('extension'),
      favorites: outcome.get<int>('favorites'),
      favouriteLink: outcome.get<String>('favouriteLink'),
      favourited: outcome.get<bool>('favourited'),
      fileSize: outcome.get<String>('fileSize'),
      noteLink: outcome.get<String>('noteLink'),
      posted: outcome.get<DateTime>('posted'),
      preview: outcome.get<String>('preview'),
      resolution: outcome.get<String>('resolution'),
      species: outcome.get<String>('species'),
      tags: outcome.get<List<String>>('tags'),
      theme: outcome.get<String>('theme'),
      type: SubmissionType.byName(outcome.get<String>('type')),
      uploaderAvatar: outcome.get<String>('uploaderAvatar'),
      uploaderName: outcome.get<String>('uploaderName'),
      views: outcome.get<int>('views'),
      failed: outcome.failed,
    );
  }
}
