// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

/// The kind of content a submission holds.
enum SubmissionType {
  image,
  text,
  audio,
  flash;

  static SubmissionType? byName(String? name) =>
      name == null ? null : values.asNameMap()[name];
}
