import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:furlovin/parser/data/document.dart';

const String rulesDir = 'assets/rules';
const String libDir = 'lib';
const String manifestPath = 'lib/parser/data/manifest.rules.dart';

const String freezedUrl = 'package:freezed_annotation/freezed_annotation.dart';
const String parserUrl = 'package:furlovin/parser/parser.dart';

const Map<String, String> builtInTypes = {
  'string': 'String',
  'int': 'int',
  'float': 'double',
  'timestamp': 'DateTime',
  'bool': 'bool',
};

const Set<String> knownOps = {
  'select',
  'selectAll',
  'closest',
  'previous',
  'attr',
  'text',
  'class',
  'regex',
  'replace',
  'index',
  'trim',
  'html',
  'url',
  'literal',
};

void main(List<String> arguments) {
  final List<File> versions =
      Directory(rulesDir)
          .listSync()
          .whereType<File>()
          .where((e) => RegExp(r'v\d+\.yaml$').hasMatch(e.path))
          .toList()
        ..sort((a, b) => _version(a).compareTo(_version(b)));
  if (versions.isEmpty) {
    stderr.writeln('no $rulesDir/v<n>.yaml found');
    exit(1);
  }
  final File source = versions.last;

  final Map<String, Object?> json = decodeRules(source.readAsStringSync());
  final int schema = (json['schema']! as num).toInt();
  if (schema != _version(source)) {
    stderr.writeln(
      '${source.path} declares schema $schema but is named v${_version(source)}',
    );
    exit(1);
  }
  final Map<String, Object?> entities = (json['entities']! as Map)
      .cast<String, Object?>();

  final List<String> problems = [];
  final Map<String, List<Map<String, Object?>>> refs = {};
  final Map<String, Object?> declared = ((json['refs'] as Map?) ?? const {})
      .cast<String, Object?>();
  for (final MapEntry<String, Object?> ref in declared.entries) {
    refs[ref.key] = [
      for (final Object? step in ref.value! as List)
        (step! as Map).cast<String, Object?>(),
    ];
  }

  final Map<String, Object?> enums = ((json['enums'] as Map?) ?? const {})
      .cast<String, Object?>();

  final Map<String, List<RuleField>> parsed = {
    for (final MapEntry<String, Object?> entity in entities.entries)
      entity.key: _fields(entity.key, entity.value, refs, enums, problems),
  };

  final Map<String, Object?> pages = ((json['pages'] as Map?) ?? const {})
      .cast<String, Object?>();
  for (final MapEntry<String, Object?> page in pages.entries) {
    final Map<String, Object?> spec = (page.value! as Map)
        .cast<String, Object?>();
    if ((spec['feature'] as String? ?? '').isEmpty) {
      problems.add('page ${page.key}: missing "feature"');
    }
    final Map<String, Object?> slots = ((spec['slots'] as Map?) ?? const {})
        .cast<String, Object?>();
    if (slots.isEmpty) problems.add('page ${page.key}: no slots');
    for (final MapEntry<String, Object?> slot in slots.entries) {
      final Map<String, Object?> shape = (slot.value! as Map)
          .cast<String, Object?>();
      final String entity = shape['entity'] as String? ?? '';
      if (!entities.containsKey(entity)) {
        problems.add(
          'page ${page.key}, slot ${slot.key}: unknown entity "$entity"',
        );
      }
      if ((shape['selector'] as String? ?? '').isEmpty) {
        problems.add('page ${page.key}, slot ${slot.key}: missing selector');
      }
    }
  }

  if (problems.isNotEmpty) {
    stderr.writeln('rule file is invalid:');
    for (final String problem in problems) {
      stderr.writeln('  $problem');
    }
    exit(1);
  }

  header =
      '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
      '// Generated by tool/generate_rules.dart\n'
      '// Rules schema $schema\n'
      '\n';

  final Set<String> written = {};

  for (final MapEntry<String, Object?> entry in enums.entries) {
    final Map<String, Object?> spec = (entry.value! as Map)
        .cast<String, Object?>();
    final String feature = spec['feature'] as String? ?? '';
    if (feature.isEmpty) {
      stderr.writeln('${entry.key}: missing "feature"');
      exit(1);
    }
    final String file = '${_snake(entry.key)}.rules.dart';
    final String path = '$libDir/$feature/data/$file';
    _write(
      path,
      Library(
        (b) => b.body.add(
          _enum(entry.key, spec['description'] as String?, [
            for (final Object? value in spec['values']! as List) '$value',
          ]),
        ),
      ),
    );
    written.add(path);
  }

  for (final MapEntry<String, List<RuleField>> entry in parsed.entries) {
    final String feature =
        ((entities[entry.key]! as Map).cast<String, Object?>()['feature']
            as String?) ??
        '';
    if (feature.isEmpty) {
      stderr.writeln('${entry.key}: missing "feature"');
      exit(1);
    }
    final String file = '${_snake(entry.key)}.rules.dart';
    final String path = '$libDir/$feature/data/$file';
    _write(
      path,
      Library(
        (b) => b
          ..directives.add(
            Directive.part(file.replaceAll('.dart', '.freezed.dart')),
          )
          ..body.add(
            _model(
              entry.key,
              (entities[entry.key]! as Map)
                      .cast<String, Object?>()['description']
                  as String?,
              entry.value,
            ),
          ),
      ),
    );
    written.add(path);
  }

  final Map<String, List<MapEntry<String, Map<String, Object?>>>> byFeature =
      {};
  for (final MapEntry<String, Object?> page in pages.entries) {
    final Map<String, Object?> spec = (page.value! as Map)
        .cast<String, Object?>();
    byFeature
        .putIfAbsent(spec['feature']! as String, () => [])
        .add(MapEntry(page.key, spec));
  }
  for (final MapEntry<String, List<MapEntry<String, Map<String, Object?>>>>
      feature
      in byFeature.entries) {
    final String path = '$libDir/${feature.key}/data/pages.rules.dart';
    final Set<String> used = {
      for (final MapEntry<String, Map<String, Object?>> page in feature.value)
        for (final Object? slot
            in ((page.value['slots'] as Map?) ?? const {}).values)
          (slot! as Map).cast<String, Object?>()['entity']! as String,
    };
    _write(
      path,
      Library(
        (b) => b
          ..directives.addAll([
            for (final String entity in used.toList()..sort())
              Directive.import(
                _entityImport(
                  entity,
                  (entities[entity]! as Map).cast<String, Object?>()['feature']!
                      as String,
                ),
              ),
            Directive.import('package:furlovin/parser/parser.dart'),
          ])
          ..body.addAll([
            for (final MapEntry<String, Map<String, Object?>> page
                in feature.value)
              _slots(page.key, page.value),
          ]),
      ),
    );
    written.add(path);
  }

  _write(
    manifestPath,
    Library(
      (b) => b.body.addAll([
        Field(
          (b) => b
            ..name = 'generatedSchema'
            ..modifier = FieldModifier.constant
            ..type = refer('int')
            ..assignment = literalNum(schema).code,
        ),
        Field(
          (b) => b
            ..name = 'rulesAsset'
            ..modifier = FieldModifier.constant
            ..type = refer('String')
            ..assignment = literalString(source.path).code,
        ),
        Field(
          (b) => b
            ..name = 'ruleManifest'
            ..modifier = FieldModifier.constant
            ..type = refer('Map<String, List<String>>')
            ..assignment = literalConstMap({
              for (final MapEntry<String, List<RuleField>> entry
                  in parsed.entries)
                entry.key: [
                  for (final RuleField field in entry.value) field.name,
                ]..sort(),
            }).code,
        ),
      ]),
    ),
  );
  written.add(manifestPath);

  final List<String> removed = [];
  for (final FileSystemEntity entity in Directory(
    libDir,
  ).listSync(recursive: true)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.rules.dart')) continue;
    if (written.contains(entity.path)) continue;
    entity.deleteSync();
    removed.add(entity.path);
    final File part = File(
      entity.path.replaceAll('.rules.dart', '.rules.freezed.dart'),
    );
    if (part.existsSync()) part.deleteSync();
  }

  for (final String path in written) {
    stdout.writeln('  wrote $path');
  }
  for (final String path in removed) {
    stdout.writeln('  removed $path');
  }
  stdout.writeln('${parsed.length} entities, schema $schema');
}

String header = '';

void _write(String path, Library library) {
  final String emitted = library
      .accept(DartEmitter(allocator: Allocator(), orderDirectives: true))
      .toString();
  File(path)
    ..createSync(recursive: true)
    ..writeAsStringSync(
      header +
          DartFormatter(languageVersion: DartFormatter.latestLanguageVersion)
              .format(emitted),
    );
}

String? _enumUrl(String name, Map<String, Object?> enums) {
  final Map<String, Object?>? spec = (enums[name] as Map?)
      ?.cast<String, Object?>();
  final String? feature = spec?['feature'] as String?;
  if (feature == null) return null;
  return 'package:furlovin/$feature/data/${_snake(name)}.rules.dart';
}

int _version(File file) =>
    int.parse(RegExp(r'v(\d+)\.yaml$').firstMatch(file.path)!.group(1)!);

Class _slots(String page, Map<String, Object?> spec) {
  final Map<String, Object?> slots = ((spec['slots'] as Map?) ?? const {})
      .cast<String, Object?>();
  return Class(
    (b) => b
      ..name = '${_pascal(page)}Slots'
      ..abstract = true
      ..modifier = ClassModifier.final$
      ..fields.addAll([
        for (final MapEntry<String, Object?> slot in slots.entries)
          _slot(page, slot.key, (slot.value! as Map).cast<String, Object?>()),
      ]),
  );
}

Field _slot(String page, String name, Map<String, Object?> shape) {
  final String entity = shape['entity']! as String;
  final String model = _pascal(entity);
  final String kind = (shape['list'] as bool? ?? false)
      ? 'ListSlot'
      : 'SingleSlot';
  return Field(
    (b) => b
      ..name = name
      ..static = true
      ..modifier = FieldModifier.constant
      ..type = refer('$kind<$model>')
      ..assignment = refer(kind).constInstance([
        literalString(page),
        literalString(name),
        literalString(entity),
        refer('$model.fromOutcome'),
      ]).code,
  );
}

String _entityImport(String entity, String feature) =>
    'package:furlovin/$feature/data/${_snake(entity)}.rules.dart';

String _snake(String value) => value
    .replaceAllMapped(RegExp(r'([a-z0-9])([A-Z])'), (m) => '${m[1]}_${m[2]}')
    .toLowerCase();

List<Map<String, Object?>> _expand(
  Object? pipeline,
  Map<String, List<Map<String, Object?>>> refs,
  String where,
  List<String> problems,
) {
  final List<Map<String, Object?>> steps = [];
  for (final Object? step in pipeline! as List) {
    final Map<String, Object?> spec = (step! as Map).cast<String, Object?>();
    final Object? reference = spec[r'$ref'];
    if (reference == null) {
      steps.add(spec);
      continue;
    }
    final List<Map<String, Object?>>? resolved = refs[reference];
    if (resolved == null) {
      problems.add('$where: unknown ref "$reference"');
      continue;
    }
    steps.addAll(resolved);
  }
  return steps;
}

List<RuleField> _fields(
  String entity,
  Object? spec,
  Map<String, List<Map<String, Object?>>> refs,
  Map<String, Object?> enums,
  List<String> problems,
) {
  final Map<String, Object?> fields =
      ((spec! as Map).cast<String, Object?>()['fields']! as Map)
          .cast<String, Object?>();
  final List<RuleField> result = [];

  for (final MapEntry<String, Object?> field in fields.entries) {
    final Map<String, Object?> value = (field.value! as Map)
        .cast<String, Object?>();
    final List<Object?> alternatives = (value['steps']! as List).cast();
    final String declared = value['type'] as String? ?? 'string';
    final String? dartType = builtInTypes[declared];
    final bool isEnum = dartType == null;
    if (isEnum && !enums.containsKey(declared)) {
      problems.add('$entity.${field.key}: unknown type "$declared"');
    }

    for (final Object? alternative in alternatives) {
      final String where = '$entity.${field.key}';
      final List<Map<String, Object?>> steps = _expand(
        alternative,
        refs,
        where,
        problems,
      );
      if (steps.isEmpty) {
        problems.add('$where: empty pipeline');
        continue;
      }
      for (final Map<String, Object?> spec in steps) {
        final String op = spec['op'] as String? ?? '';
        if (!knownOps.contains(op)) {
          problems.add('$where: unknown op "$op"');
        }
        if (op == 'regex' || op == 'replace') {
          try {
            RegExp(spec['pattern']! as String);
          } on FormatException catch (e) {
            problems.add('$where: bad regex: $e');
          }
        }
      }
    }

    final bool repeated = value['repeated'] as bool? ?? false;
    result.add(
      RuleField(
        name: field.key,
        type: repeated
            ? 'List<${dartType ?? declared}>'
            : (dartType ?? declared),
        required: value['required'] as bool? ?? false,
        description: value['description'] as String?,
        typeUrl: isEnum ? _enumUrl(declared, enums) : null,
        element: repeated ? (dartType ?? declared) : null,
      ),
    );
  }

  result.sort((a, b) {
    if (a.required != b.required) return a.required ? -1 : 1;
    return a.name.compareTo(b.name);
  });
  return result;
}

Enum _enum(String name, String? description, List<String> values) => Enum(
  (b) => b
    ..name = name
    ..docs.addAll(_docs(description))
    ..values.addAll([
      for (final String value in values) EnumValue((b) => b..name = value),
    ])
    ..methods.add(
      Method(
        (b) => b
          ..name = 'byName'
          ..static = true
          ..returns = refer('$name?')
          ..requiredParameters.add(
            Parameter(
              (b) => b
                ..name = 'name'
                ..type = refer('String?'),
            ),
          )
          ..lambda = true
          ..body = const Code('name == null ? null : values.asNameMap()[name]'),
      ),
    ),
);

List<String> _docs(String? description) => description == null
    ? const []
    : description.split('\n').map((e) => '/// $e').toList();

Class _model(String entity, String? description, List<RuleField> fields) {
  final String name = _pascal(entity);
  return Class(
    (b) => b
      ..name = name
      ..abstract = true
      ..docs.addAll(_docs(description))
      ..annotations.add(refer('freezed', freezedUrl))
      ..mixins.add(refer('_\$$name'))
      ..constructors.addAll([
        Constructor(
          (b) => b
            ..name = '_'
            ..constant = true,
        ),
        Constructor(
          (b) => b
            ..factory = true
            ..constant = true
            ..redirect = refer('_$name')
            ..optionalParameters.addAll([
              for (final RuleField field in fields)
                Parameter(
                  (b) => b
                    ..name = field.name
                    ..named = true
                    ..required = field.required
                    ..docs.addAll(_docs(field.description))
                    ..type = refer(
                      field.required ? field.type : '${field.type}?',
                      field.typeUrl,
                    ),
                ),
              Parameter(
                (b) => b
                  ..name = 'failed'
                  ..named = true
                  ..type = refer('Map<String, ParseException>', parserUrl)
                  ..annotations.add(
                    refer('Default', freezedUrl).call([literalConstMap({})]),
                  ),
              ),
            ]),
        ),
      ])
      ..fields.add(
        Field(
          (b) => b
            ..name = 'entity'
            ..static = true
            ..modifier = FieldModifier.constant
            ..type = refer('String')
            ..assignment = literalString(entity).code,
        ),
      )
      ..methods.add(_fromOutcome(name, fields)),
  );
}

Expression _read(RuleField field) {
  final Expression raw = refer('outcome')
      .property('get')
      .call(
        [literalString(field.name)],
        {},
        [refer(field.isEnum ? 'String' : field.type)],
      );
  return field.isEnum
      ? refer(field.type, field.typeUrl).property('byName').call([raw])
      : raw;
}

Method _fromOutcome(String name, List<RuleField> fields) => Method(
  (b) => b
    ..name = 'fromOutcome'
    ..static = true
    ..returns = refer('$name?')
    ..requiredParameters.add(
      Parameter(
        (b) => b
          ..name = 'outcome'
          ..type = refer('ParseOutcome', parserUrl),
      ),
    )
    ..body = Block.of([
      for (final RuleField field in fields.where((e) => e.required)) ...[
        declareFinal(
          field.name,
          type: refer('${field.type}?'),
        ).assign(_read(field)).statement,
        Code('if (${field.name} == null) return null;'),
      ],
      refer(name)
          .newInstance([], {
            for (final RuleField field in fields)
              field.name: field.required ? refer(field.name) : _read(field),
            'failed': refer('outcome').property('failed'),
          })
          .returned
          .statement,
    ]),
);

String _pascal(String value) => value
    .split(RegExp(r'[_\s-]+'))
    .where((e) => e.isNotEmpty)
    .map((e) => e[0].toUpperCase() + e.substring(1))
    .join();

class RuleField {
  const RuleField({
    required this.name,
    required this.type,
    required this.required,
    this.description,
    this.typeUrl,
    this.element,
  });

  final String name;
  final String type;
  final bool required;
  final String? description;
  final String? typeUrl;
  final String? element;

  bool get isEnum => typeUrl != null && element == null;
}
