import 'dart:io';

import 'package:code_builder/code_builder.dart';
import 'package:dart_style/dart_style.dart';
import 'package:furlovin/parser/data/document.dart';

const String rulesDir = 'assets/rules';
const String libDir = 'lib';
const String manifestPath = 'lib/parser/data/manifest.rules.dart';

const String freezedUrl = 'package:freezed_annotation/freezed_annotation.dart';
const String parserUrl = 'package:furlovin/parser/parser.dart';

const Map<String, String> builtInTypes = {
  'string': 'String',
  'int': 'int',
  'float': 'double',
  'timestamp': 'DateTime',
  'bool': 'bool',
};

const Set<String> knownOps = {
  'select',
  'selectAll',
  'closest',
  'previous',
  'labeled',
  'attr',
  'text',
  'class',
  'regex',
  'replace',
  'index',
  'trim',
  'html',
  'url',
  'literal',
};

void main(List<String> arguments) {
  final List<File> versions =
      Directory(rulesDir)
          .listSync()
          .whereType<File>()
          .where((e) => RegExp(r'v\d+\.yaml$').hasMatch(e.path))
          .toList()
        ..sort((a, b) => _version(a).compareTo(_version(b)));
  if (versions.isEmpty) {
    stderr.writeln('no $rulesDir/v<n>.yaml found');
    exit(1);
  }
  final File source = versions.last;
  final Map<String, Object?> json = decodeRules(source.readAsStringSync());
  final int schema = (json['schema']! as num).toInt();
  if (schema != _version(source)) {
    stderr.writeln(
      '${source.path} declares schema $schema but is named v${_version(source)}',
    );
    exit(1);
  }

  final Map<String, Object?> enums = _map(json['enums']);
  final Map<String, Object?> refs = _map(json['refs']);
  final Map<String, Map<String, Object?>> types = {
    for (final MapEntry<String, Object?> entry in _map(json['types']).entries)
      entry.key: _map(entry.value),
  };

  final List<String> problems = [];
  for (final MapEntry<String, Map<String, Object?>> type in types.entries) {
    if ((type.value['feature'] as String? ?? '').isEmpty) {
      problems.add('${type.key}: missing "feature"');
    }
    for (final MapEntry<String, Object?> field in _map(
      type.value['fields'],
    ).entries) {
      _check(
        '${type.key}.${field.key}',
        _map(field.value),
        types,
        enums,
        refs,
        problems,
      );
    }
  }
  if (problems.isNotEmpty) {
    stderr.writeln('rule file is invalid:');
    for (final String problem in problems) {
      stderr.writeln('  $problem');
    }
    exit(1);
  }

  header =
      '// GENERATED CODE - DO NOT MODIFY BY HAND\n'
      '// Generated by tool/generate_rules.dart\n'
      '// Rules schema $schema\n'
      '\n';

  final Set<String> written = {};

  for (final MapEntry<String, Object?> entry in enums.entries) {
    final Map<String, Object?> spec = _map(entry.value);
    final String path = _path(spec['feature']! as String, entry.key);
    _write(
      path,
      Library(
        (b) => b.body.add(
          _enum(entry.key, spec['description'] as String?, [
            for (final Object? value in spec['values']! as List) '$value',
          ]),
        ),
      ),
    );
    written.add(path);
  }

  final Map<String, Map<String, String>> manifest = {};
  for (final MapEntry<String, Map<String, Object?>> type in types.entries) {
    final List<ModelField> fields = [
      for (final MapEntry<String, Object?> field in _map(
        type.value['fields'],
      ).entries)
        ModelField.of(field.key, _map(field.value), types, enums),
    ]..sort();
    manifest[type.key] = {
      for (final ModelField field in fields) field.name: field.signature,
    };
    final String path = _path(type.value['feature']! as String, type.key);
    final String file = path.split('/').last;
    _write(
      path,
      Library(
        (b) => b
          ..directives.add(
            Directive.part(file.replaceAll('.dart', '.freezed.dart')),
          )
          ..body.add(
            _model(
              type.key,
              type.value['description'] as String?,
              fields,
              page: type.value['page'] as bool? ?? false,
            ),
          ),
      ),
    );
    written.add(path);
  }

  _write(
    manifestPath,
    Library(
      (b) => b.body.addAll([
        Field(
          (b) => b
            ..name = 'generatedSchema'
            ..modifier = FieldModifier.constant
            ..type = refer('int')
            ..assignment = literalNum(schema).code,
        ),
        Field(
          (b) => b
            ..name = 'rulesAsset'
            ..modifier = FieldModifier.constant
            ..type = refer('String')
            ..assignment = literalString(source.path).code,
        ),
        Field(
          (b) => b
            ..name = 'ruleManifest'
            ..modifier = FieldModifier.constant
            ..type = refer('Map<String, Map<String, String>>')
            ..assignment = literalConstMap(manifest).code,
        ),
      ]),
    ),
  );
  written.add(manifestPath);

  final List<String> removed = [];
  for (final FileSystemEntity entity in Directory(
    libDir,
  ).listSync(recursive: true)) {
    if (entity is! File) continue;
    if (!entity.path.endsWith('.rules.dart')) continue;
    if (written.contains(entity.path)) continue;
    entity.deleteSync();
    removed.add(entity.path);
    final File part = File(
      entity.path.replaceAll('.rules.dart', '.rules.freezed.dart'),
    );
    if (part.existsSync()) part.deleteSync();
  }

  for (final String path in written) {
    stdout.writeln('  wrote $path');
  }
  for (final String path in removed) {
    stdout.writeln('  removed $path');
  }
  stdout.writeln('${types.length} types, schema $schema');
}

String header = '';

Map<String, Object?> _map(Object? json) =>
    ((json as Map?) ?? const {}).cast<String, Object?>();

List<Object?> _list(Object? json) => (json as List?) ?? const [];

void _check(
  String where,
  Map<String, Object?> field,
  Map<String, Map<String, Object?>> types,
  Map<String, Object?> enums,
  Map<String, Object?> refs,
  List<String> problems,
) {
  final String type = field['type'] as String? ?? 'string';
  final bool nested = types.containsKey(type);
  if (!nested && !builtInTypes.containsKey(type) && !enums.containsKey(type)) {
    problems.add('$where: unknown type "$type"');
  }
  final String presence = field['presence'] as String? ?? 'optional';
  if (!{'required', 'expected', 'optional'}.contains(presence)) {
    problems.add('$where: unknown presence "$presence"');
  }
  final bool list = field['list'] as bool? ?? false;
  if ((nested || list) && _list(field['at']).isEmpty) {
    problems.add('$where: needs at');
  }
  if (nested && field.containsKey('read')) {
    problems.add('$where: a type field cannot read');
  }
  if (!nested && _list(field['read']).isEmpty) {
    problems.add('$where: needs read');
  }
  for (final Object? alternative in _list(field['read'])) {
    final List<Object?> steps = _list(alternative);
    if (steps.isEmpty) problems.add('$where: empty pipeline');
    for (final Object? step in steps) {
      final Map<String, Object?> spec = _map(step);
      if (spec[r'$ref'] case final Object reference) {
        if (!refs.containsKey(reference)) {
          problems.add('$where: unknown ref "$reference"');
        }
        continue;
      }
      final String op = spec['op'] as String? ?? '';
      if (!knownOps.contains(op)) problems.add('$where: unknown op "$op"');
      if (op == 'regex' || op == 'replace') {
        try {
          RegExp(spec['pattern']! as String);
        } on FormatException catch (e) {
          problems.add('$where: bad regex: $e');
        }
      }
    }
  }
}

void _write(String path, Library library) {
  final String emitted = library
      .accept(
        DartEmitter(
          allocator: Allocator(),
          orderDirectives: true,
          useNullSafetySyntax: true,
        ),
      )
      .toString();
  File(path)
    ..createSync(recursive: true)
    ..writeAsStringSync(
      header +
          DartFormatter(languageVersion: DartFormatter.latestLanguageVersion)
              .format(emitted),
    );
}

String _path(String feature, String name) =>
    '$libDir/$feature/data/${_snake(name)}.rules.dart';

String _url(String feature, String name) =>
    'package:furlovin/$feature/data/${_snake(name)}.rules.dart';

int _version(File file) =>
    int.parse(RegExp(r'v(\d+)\.yaml$').firstMatch(file.path)!.group(1)!);

String _snake(String value) => value
    .replaceAllMapped(RegExp(r'([a-z0-9])([A-Z])'), (m) => '${m[1]}_${m[2]}')
    .toLowerCase();

String _pascal(String value) => value
    .split(RegExp(r'[_\s-]+'))
    .where((e) => e.isNotEmpty)
    .map((e) => e[0].toUpperCase() + e.substring(1))
    .join();

List<String> _docs(String? description) => description == null
    ? const []
    : description.split('\n').map((e) => '/// $e').toList();

Enum _enum(String name, String? description, List<String> values) => Enum(
  (b) => b
    ..name = name
    ..docs.addAll(_docs(description))
    ..values.addAll([
      for (final String value in values) EnumValue((b) => b..name = value),
    ])
    ..methods.add(
      Method(
        (b) => b
          ..name = 'byName'
          ..static = true
          ..returns = refer('$name?')
          ..requiredParameters.add(
            Parameter(
              (b) => b
                ..name = 'name'
                ..type = refer('String?'),
            ),
          )
          ..lambda = true
          ..body = const Code('name == null ? null : values.asNameMap()[name]'),
      ),
    ),
);

enum FieldKind { scalar, enumeration, nested }

class ModelField implements Comparable<ModelField> {
  const ModelField({
    required this.name,
    required this.kind,
    required this.declared,
    required this.element,
    required this.list,
    required this.required,
    this.description,
  });

  factory ModelField.of(
    String name,
    Map<String, Object?> json,
    Map<String, Map<String, Object?>> types,
    Map<String, Object?> enums,
  ) {
    final String declared = json['type'] as String? ?? 'string';
    final FieldKind kind = types.containsKey(declared)
        ? FieldKind.nested
        : enums.containsKey(declared)
        ? FieldKind.enumeration
        : FieldKind.scalar;
    return ModelField(
      name: name,
      kind: kind,
      declared: declared,
      element: switch (kind) {
        FieldKind.scalar => refer(builtInTypes[declared]!),
        FieldKind.enumeration => refer(
          declared,
          _url(_map(enums[declared])['feature']! as String, declared),
        ),
        FieldKind.nested => refer(
          _pascal(declared),
          _url(types[declared]!['feature']! as String, declared),
        ),
      },
      list: json['list'] as bool? ?? false,
      required: json['presence'] == 'required',
      description: json['description'] as String?,
    );
  }

  final String name;
  final FieldKind kind;
  final String declared;
  final Reference element;
  final bool list;
  final bool required;
  final String? description;

  String get signature =>
      '${list ? '[$declared]' : declared}${required ? '!' : ''}';

  Reference get dartType => list
      ? TypeReference(
          (b) => b
            ..symbol = 'List'
            ..types.add(element),
        )
      : TypeReference(
          (b) => b
            ..symbol = element.symbol
            ..url = element.url
            ..isNullable = !required,
        );

  Code read(String outcome) => Code.scope((allocate) {
    final String type = allocate(element);
    final String raw = "$outcome['$name']";
    if (list) {
      return switch (kind) {
        FieldKind.scalar =>
          '[...?($raw as List<Object?>?)?.whereType<$type>()]',
        FieldKind.enumeration =>
          '[for (final Object? item in ($raw as List<Object?>?) ?? const []) '
              '?$type.byName(item as String?)]',
        FieldKind.nested =>
          '[for (final Object? item in ($raw as List<Object?>?) ?? const []) '
              'if (item is ${allocate(refer('ParseOutcome', parserUrl))}) '
              '?$type.fromOutcome(item)]',
      };
    }
    return switch (kind) {
      FieldKind.scalar => "$outcome.get<$type>('$name')",
      FieldKind.enumeration => "$type.byName($outcome.get<String>('$name'))",
      FieldKind.nested =>
        'switch ($raw) { '
            "final ${allocate(refer('ParseOutcome', parserUrl))} child => "
            '$type.fromOutcome(child), _ => null }',
    };
  });

  @override
  int compareTo(ModelField other) {
    if (required != other.required) return required ? -1 : 1;
    return name.compareTo(other.name);
  }
}

Class _model(
  String type,
  String? description,
  List<ModelField> fields, {
  required bool page,
}) {
  final String name = _pascal(type);
  return Class(
    (b) => b
      ..name = name
      ..abstract = true
      ..docs.addAll(_docs(description))
      ..annotations.add(refer('freezed', freezedUrl))
      ..mixins.add(refer('_\$$name'))
      ..constructors.addAll([
        Constructor(
          (b) => b
            ..name = '_'
            ..constant = true,
        ),
        Constructor(
          (b) => b
            ..factory = true
            ..constant = true
            ..redirect = refer('_$name')
            ..optionalParameters.addAll([
              for (final ModelField field in fields)
                Parameter(
                  (b) => b
                    ..name = field.name
                    ..named = true
                    ..required = field.required && !field.list
                    ..docs.addAll(_docs(field.description))
                    ..annotations.addAll([
                      if (field.list)
                        refer(
                          'Default',
                          freezedUrl,
                        ).call([literalConstList([])]),
                    ])
                    ..type = field.dartType,
                ),
              Parameter(
                (b) => b
                  ..name = 'failed'
                  ..named = true
                  ..type = refer('Map<String, ParseException>', parserUrl)
                  ..annotations.add(
                    refer('Default', freezedUrl).call([literalConstMap({})]),
                  ),
              ),
              if (page)
                Parameter(
                  (b) => b
                    ..name = 'errors'
                    ..named = true
                    ..type = refer('DocumentErrors?', parserUrl),
                ),
            ]),
        ),
      ])
      ..fields.add(
        Field(
          (b) => b
            ..name = 'ruleType'
            ..static = true
            ..modifier = FieldModifier.constant
            ..type = refer('String')
            ..assignment = literalString(type).code,
        ),
      )
      ..methods.add(_fromOutcome(name, fields, page: page)),
  );
}

Method _fromOutcome(
  String name,
  List<ModelField> fields, {
  required bool page,
}) => Method(
  (b) => b
    ..name = 'fromOutcome'
    ..static = true
    ..returns = refer('$name?')
    ..requiredParameters.add(
      Parameter(
        (b) => b
          ..name = 'outcome'
          ..type = refer('ParseOutcome', parserUrl),
      ),
    )
    ..optionalParameters.addAll([
      if (page)
        Parameter(
          (b) => b
            ..name = 'errors'
            ..named = true
            ..type = refer('DocumentErrors?', parserUrl),
        ),
    ])
    ..body = Block.of([
      for (final ModelField field in fields.where(
        (e) => e.required && !e.list,
      )) ...[
        declareFinal(
          field.name,
          type: TypeReference(
            (b) => b
              ..symbol = field.element.symbol
              ..url = field.element.url
              ..isNullable = true,
          ),
        ).assign(CodeExpression(field.read('outcome'))).statement,
        Code('if (${field.name} == null) return null;'),
      ],
      refer(name)
          .newInstance([], {
            for (final ModelField field in fields)
              field.name: field.required && !field.list
                  ? refer(field.name)
                  : CodeExpression(field.read('outcome')),
            'failed': refer('outcome').property('failed'),
            if (page) 'errors': refer('errors'),
          })
          .returned
          .statement,
    ]),
);
