// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'contact.rules.freezed.dart';

/// A way to reach a member, as listed on their profile.
@freezed
abstract class Contact with _$Contact {
  const Contact._();

  const factory Contact({
    /// The service the entry points at.
    required String kind,

    /// The handle or address the member gave.
    required String value,

    /// Absolute url of the badge the site draws for the service.
    String? icon,

    /// The service name as the site writes it.
    String? label,

    /// Absolute url the entry points at, where the site made
    /// one. Handles the site cannot link carry no url.
    String? link,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Contact;

  static const String entity = 'contact';

  static Contact? fromOutcome(ParseOutcome outcome) {
    final String? kind = outcome.get<String>('kind');
    if (kind == null) return null;
    final String? value = outcome.get<String>('value');
    if (value == null) return null;
    return Contact(
      kind: kind,
      value: value,
      icon: outcome.get<String>('icon'),
      label: outcome.get<String>('label'),
      link: outcome.get<String>('link'),
      failed: outcome.failed,
    );
  }
}
