// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'fact.rules.freezed.dart';

/// A question the site asks on a profile, and its answer.
@freezed
abstract class Fact with _$Fact {
  const Fact._();

  const factory Fact({
    /// The question, as the site words it.
    required String label,

    /// The answer the member gave.
    required String value,

    /// Which block of questions the row sits in. The site separates the
    /// availability answers from the rest and renders the rest smaller.
    String? group,
    @Default(const {}) Map<String, String> failed,
  }) = _Fact;

  static const String entity = 'fact';

  static Fact? fromOutcome(ParseOutcome outcome) {
    final String? label = outcome.get<String>('label');
    if (label == null) return null;
    final String? value = outcome.get<String>('value');
    if (value == null) return null;
    return Fact(
      label: label,
      value: value,
      group: outcome.get<String>('group'),
      failed: outcome.failed,
    );
  }
}
