// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_rating.rules.dart';

part 'featured_submission.rules.freezed.dart';

@freezed
abstract class FeaturedSubmission with _$FeaturedSubmission {
  const FeaturedSubmission._();

  const factory FeaturedSubmission({
    required int id,
    required String link,
    required SubmissionRating rating,
    required String thumbnail,
    String? title,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _FeaturedSubmission;

  static const String ruleType = 'featuredSubmission';

  static FeaturedSubmission? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    final String? link = outcome.get<String>('link');
    if (link == null) return null;
    final SubmissionRating? rating = SubmissionRating.byName(
      outcome.get<String>('rating'),
    );
    if (rating == null) return null;
    final String? thumbnail = outcome.get<String>('thumbnail');
    if (thumbnail == null) return null;
    return FeaturedSubmission(
      id: id,
      link: link,
      rating: rating,
      thumbnail: thumbnail,
      title: outcome.get<String>('title'),
      failed: outcome.failed,
    );
  }
}
