// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';
import 'package:furlovin/user/data/contact.rules.dart';
import 'package:furlovin/user/data/fact.rules.dart';
import 'package:furlovin/user/data/shout.rules.dart';
import 'package:furlovin/user/data/user.rules.dart';

abstract final class UserSlots {
  static const SingleSlot<User> profile = SingleSlot(
    'user',
    'profile',
    'user',
    User.fromOutcome,
  );

  static const ListSlot<Contact> contacts = ListSlot(
    'user',
    'contacts',
    'contact',
    Contact.fromOutcome,
  );

  static const ListSlot<SubmissionPreview> gallery = ListSlot(
    'user',
    'gallery',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );

  static const ListSlot<SubmissionPreview> favorites = ListSlot(
    'user',
    'favorites',
    'submissionPreview',
    SubmissionPreview.fromOutcome,
  );

  static const ListSlot<Shout> shouts = ListSlot(
    'user',
    'shouts',
    'shout',
    Shout.fromOutcome,
  );

  static const ListSlot<Fact> facts = ListSlot(
    'user',
    'facts',
    'fact',
    Fact.fromOutcome,
  );
}
