// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'shout.rules.freezed.dart';

/// A message left on a member profile.
@freezed
abstract class Shout with _$Shout {
  const Shout._();

  const factory Shout({
    /// The message's numeric identifier.
    required int id,

    /// The url form of the writer name.
    String? author,

    /// Absolute url of the writer's avatar.
    String? authorAvatar,

    /// The writer name as displayed.
    String? authorName,

    /// The message, as markup rather than text.
    String? body,

    /// When the message was left.
    DateTime? posted,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Shout;

  static const String entity = 'shout';

  static Shout? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    return Shout(
      id: id,
      author: outcome.get<String>('author'),
      authorAvatar: outcome.get<String>('authorAvatar'),
      authorName: outcome.get<String>('authorName'),
      body: outcome.get<String>('body'),
      posted: outcome.get<DateTime>('posted'),
      failed: outcome.failed,
    );
  }
}
