// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'user.rules.freezed.dart';

/// A member as their profile page carries them.
@freezed
abstract class User with _$User {
  const User._();

  const factory User({
    /// The url form of the name, lowercased and with underscores removed.
    required String name,

    /// Absolute url of the avatar.
    String? avatar,

    /// Absolute url of the banner across the top of the profile.
    String? banner,

    /// How many comments the member has received.
    int? commentsEarned,

    /// How many comments the member has written.
    int? commentsMade,

    /// The name as displayed.
    String? displayName,

    /// How many submissions the member has favourited.
    int? favorites,

    /// How many journals the member has posted.
    int? journals,

    /// The profile text, as markup rather than text.
    String? profile,

    /// When the account was made.
    DateTime? registered,

    /// How many submissions the member has posted.
    int? submissions,

    /// The account class the site marks the name with.
    String? symbol,

    /// The one line the member writes under their name.
    String? title,

    /// How many times the profile has been viewed.
    int? views,

    /// How many members watch this one.
    int? watchedBy,

    /// How many members this one watches.
    int? watching,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _User;

  static const String ruleType = 'user';

  static User? fromOutcome(ParseOutcome outcome) {
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return User(
      name: name,
      avatar: outcome.get<String>('avatar'),
      banner: outcome.get<String>('banner'),
      commentsEarned: outcome.get<int>('commentsEarned'),
      commentsMade: outcome.get<int>('commentsMade'),
      displayName: outcome.get<String>('displayName'),
      favorites: outcome.get<int>('favorites'),
      journals: outcome.get<int>('journals'),
      profile: outcome.get<String>('profile'),
      registered: outcome.get<DateTime>('registered'),
      submissions: outcome.get<int>('submissions'),
      symbol: outcome.get<String>('symbol'),
      title: outcome.get<String>('title'),
      views: outcome.get<int>('views'),
      watchedBy: outcome.get<int>('watchedBy'),
      watching: outcome.get<int>('watching'),
      failed: outcome.failed,
    );
  }
}
