// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';
import 'package:furlovin/submission/data/submission_preview.rules.dart';
import 'package:furlovin/user/data/contact.rules.dart';
import 'package:furlovin/user/data/fact.rules.dart';
import 'package:furlovin/user/data/shout.rules.dart';
import 'package:furlovin/user/data/user.rules.dart';

part 'user_document.rules.freezed.dart';

@freezed
abstract class UserDocument with _$UserDocument {
  const UserDocument._();

  const factory UserDocument({
    required User user,
    @Default(const []) List<Contact> contacts,
    @Default(const []) List<Fact> facts,
    @Default(const []) List<SubmissionPreview> favorites,
    @Default(const []) List<SubmissionPreview> gallery,
    @Default(const []) List<Shout> shouts,
    @Default(const {}) Map<String, ParseException> failed,
    ReadReport? report,
  }) = _UserDocument;

  static const String ruleType = 'userDocument';

  static UserDocument? fromOutcome(ParseOutcome outcome, {ReadReport? report}) {
    final User? user = switch (outcome['user']) {
      final ParseOutcome child => User.fromOutcome(child),
      _ => null,
    };
    if (user == null) return null;
    return UserDocument(
      user: user,
      contacts: [
        for (final Object? item
            in (outcome['contacts'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Contact.fromOutcome(item),
      ],
      facts: [
        for (final Object? item
            in (outcome['facts'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Fact.fromOutcome(item),
      ],
      favorites: [
        for (final Object? item
            in (outcome['favorites'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      gallery: [
        for (final Object? item
            in (outcome['gallery'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?SubmissionPreview.fromOutcome(item),
      ],
      shouts: [
        for (final Object? item
            in (outcome['shouts'] as List<Object?>?) ?? const [])
          if (item is ParseOutcome) ?Shout.fromOutcome(item),
      ],
      failed: outcome.failed,
      report: report,
    );
  }
}
