// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'comment.rules.freezed.dart';

/// A comment on a submission or a journal.
@freezed
abstract class Comment with _$Comment {
  const Comment._();

  const factory Comment({
    /// The comment's numeric identifier.
    required int id,

    /// The url form of the commenter name, lowercased and with
    /// underscores removed.
    String? author,

    /// Absolute url of the commenter's avatar.
    String? authorAvatar,

    /// The commenter name as displayed.
    String? authorName,

    /// The rendered comment, as markup rather than text.
    String? body,

    /// When the comment was posted.
    DateTime? posted,

    /// The percentage width the site renders the comment at.
    /// Replies are narrower than their parent, so this encodes depth.
    int? width,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Comment;

  static const String entity = 'comment';

  static Comment? fromOutcome(ParseOutcome outcome) {
    final int? id = outcome.get<int>('id');
    if (id == null) return null;
    return Comment(
      id: id,
      author: outcome.get<String>('author'),
      authorAvatar: outcome.get<String>('authorAvatar'),
      authorName: outcome.get<String>('authorName'),
      body: outcome.get<String>('body'),
      posted: outcome.get<DateTime>('posted'),
      width: outcome.get<int>('width'),
      failed: outcome.failed,
    );
  }
}
