// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/identity/data/viewer.rules.dart';
import 'package:furlovin/parser/parser.dart';

part 'controls_document.rules.freezed.dart';

@freezed
abstract class ControlsDocument with _$ControlsDocument {
  const ControlsDocument._();

  const factory ControlsDocument({
    Viewer? viewer,
    @Default(const {}) Map<String, ParseException> failed,
    ReadReport? report,
  }) = _ControlsDocument;

  static const String ruleType = 'controlsDocument';

  static ControlsDocument? fromOutcome(
    ParseOutcome outcome, {
    ReadReport? report,
  }) {
    return ControlsDocument(
      viewer: switch (outcome['viewer']) {
        final ParseOutcome child => Viewer.fromOutcome(child),
        _ => null,
      },
      failed: outcome.failed,
      report: report,
    );
  }
}
