// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:furlovin/identity/data/viewer.rules.dart';
import 'package:furlovin/parser/parser.dart';

abstract final class ControlsSlots {
  static const SingleSlot<Viewer> viewer = SingleSlot(
    'controls',
    'viewer',
    'viewer',
    Viewer.fromOutcome,
  );
}
