// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_rules.dart
// Rules schema 1

import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:furlovin/parser/parser.dart';

part 'viewer.rules.freezed.dart';

/// Whoever the site thinks is signed in.
@freezed
abstract class Viewer with _$Viewer {
  const Viewer._();

  const factory Viewer({
    /// The url form of the name, lowercased and with underscores
    /// removed.
    required String name,

    /// Absolute url of the avatar.
    String? avatar,

    /// How many new comments are waiting.
    int? commentAlerts,

    /// The name as displayed.
    String? displayName,

    /// How many new favourites are waiting.
    int? favouriteAlerts,

    /// How many new submissions are waiting.
    int? submissionAlerts,

    /// How many new watchers are waiting.
    int? watchAlerts,
    @Default(const {}) Map<String, ParseException> failed,
  }) = _Viewer;

  static const String ruleType = 'viewer';

  static Viewer? fromOutcome(ParseOutcome outcome) {
    final String? name = outcome.get<String>('name');
    if (name == null) return null;
    return Viewer(
      name: name,
      avatar: outcome.get<String>('avatar'),
      commentAlerts: outcome.get<int>('commentAlerts'),
      displayName: outcome.get<String>('displayName'),
      favouriteAlerts: outcome.get<int>('favouriteAlerts'),
      submissionAlerts: outcome.get<int>('submissionAlerts'),
      watchAlerts: outcome.get<int>('watchAlerts'),
      failed: outcome.failed,
    );
  }
}
